var hindu_centers = {
"type": "FeatureCollection",
"name": "Untitled layer",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Naperville, il", "description": "Naperville, il" }, "geometry": { "type": "Point", "coordinates": [ -88.206482, 41.753898 ] } },
{ "type": "Feature", "properties": { "Name": "Schaumburg, IL", "description": "Schaumburg, IL" }, "geometry": { "type": "Point", "coordinates": [ -88.036194, 42.049293 ] } },
{ "type": "Feature", "properties": { "Name": "Libertyville, IL", "description": "Libertyville, IL" }, "geometry": { "type": "Point", "coordinates": [ -87.956543, 42.265114 ] } },
{ "type": "Feature", "properties": { "Name": "Des Plains, IL", "description": "Des Plains, IL" }, "geometry": { "type": "Point", "coordinates": [ -87.819214, 41.99216 ] } },
{ "type": "Feature", "properties": { "Name": "Chicago, IL", "description": "Chicago, IL" }, "geometry": { "type": "Point", "coordinates": [ -87.626953, 41.871606 ] } },
{ "type": "Feature", "properties": { "Name": "Rockford, IL", "description": "Rockford, IL" }, "geometry": { "type": "Point", "coordinates": [ -89.005737, 42.248852 ] } },
{ "type": "Feature", "properties": { "Name": "Moline, IL", "description": "Moline, IL" }, "geometry": { "type": "Point", "coordinates": [ -90.368042, 41.488006 ] } },
{ "type": "Feature", "properties": { "Name": "Peoria, IL", "description": "Peoria, IL" }, "geometry": { "type": "Point", "coordinates": [ -89.538574, 40.680638 ] } },
{ "type": "Feature", "properties": { "Name": "Bloomington, IL", "description": "Bloomington, IL" }, "geometry": { "type": "Point", "coordinates": [ -88.978271, 40.480381 ] } },
{ "type": "Feature", "properties": { "Name": "Champaign, IL", "description": "Champaign, IL" }, "geometry": { "type": "Point", "coordinates": [ -88.198242, 40.086477 ] } },
{ "type": "Feature", "properties": { "Name": "Decatur, IL", "description": "Decatur, IL" }, "geometry": { "type": "Point", "coordinates": [ -88.934326, 39.850721 ] } },
{ "type": "Feature", "properties": { "Name": "Springfield, IL", "description": "Springfield, IL" }, "geometry": { "type": "Point", "coordinates": [ -89.626465, 39.774769 ] } },
{ "type": "Feature", "properties": { "Name": "Milwaukee, WI", "description": "Milwaukee, WI" }, "geometry": { "type": "Point", "coordinates": [ -87.945557, 43.004647 ] } },
{ "type": "Feature", "properties": { "Name": "Madison, WI", "description": "Madison, WI" }, "geometry": { "type": "Point", "coordinates": [ -89.34082, 43.052834 ] } },
{ "type": "Feature", "properties": { "Name": "Appleton, WI", "description": "Appleton, WI" }, "geometry": { "type": "Point", "coordinates": [ -88.330078, 44.21371 ] } },
{ "type": "Feature", "properties": { "Name": "Hammond, IN", "description": "Hammond, IN" }, "geometry": { "type": "Point", "coordinates": [ -87.481384, 41.590797 ] } },
{ "type": "Feature", "properties": { "Name": "Southbend, IN", "description": "Southbend, IN" }, "geometry": { "type": "Point", "coordinates": [ -86.182251, 41.658549 ] } },
{ "type": "Feature", "properties": { "Name": "Memphis, TN", "description": "Memphis, TN" }, "geometry": { "type": "Point", "coordinates": [ -90.0, 35.155846 ] } },
{ "type": "Feature", "properties": { "Name": "Nashville, TN", "description": "Nashville, TN" }, "geometry": { "type": "Point", "coordinates": [ -86.660156, 36.173357 ] } },
{ "type": "Feature", "properties": { "Name": "Knoxville, TN", "description": "Knoxville, TN" }, "geometry": { "type": "Point", "coordinates": [ -83.825684, 36.049099 ] } },
{ "type": "Feature", "properties": { "Name": "Jackson, AL", "description": "Jackson, AL" }, "geometry": { "type": "Point", "coordinates": [ -90.043945, 32.398516 ] } },
{ "type": "Feature", "properties": { "Name": "Huntsville, AL", "description": "Huntsville, AL" }, "geometry": { "type": "Point", "coordinates": [ -86.506348, 34.741612 ] } },
{ "type": "Feature", "properties": { "Name": "Cookville, TN", "description": null }, "geometry": { "type": "Point", "coordinates": [ -85.45166, 36.155618 ] } },
{ "type": "Feature", "properties": { "Name": "RTP, NC", "description": "RTP, NC" }, "geometry": { "type": "Point", "coordinates": [ -78.75, 35.89795 ] } },
{ "type": "Feature", "properties": { "Name": "Greensboro, NC", "description": "Greensboro, NC" }, "geometry": { "type": "Point", "coordinates": [ -79.815674, 36.057981 ] } },
{ "type": "Feature", "properties": { "Name": "Charlotte, NC", "description": "Charlotte, NC" }, "geometry": { "type": "Point", "coordinates": [ -80.727539, 35.245619 ] } },
{ "type": "Feature", "properties": { "Name": "Columbia, SC", "description": "Columbia, SC" }, "geometry": { "type": "Point", "coordinates": [ -80.980225, 33.988918 ] } },
{ "type": "Feature", "properties": { "Name": "Jacksonville, FL", "description": "Jacksonville, FL" }, "geometry": { "type": "Point", "coordinates": [ -81.578979, 30.306503 ] } },
{ "type": "Feature", "properties": { "Name": "Tampa, FL", "description": "Tampa, FL" }, "geometry": { "type": "Point", "coordinates": [ -82.441406, 27.955591 ] } },
{ "type": "Feature", "properties": { "Name": "Orlando, FL", "description": "Orlando, FL" }, "geometry": { "type": "Point", "coordinates": [ -81.375732, 28.545926 ] } },
{ "type": "Feature", "properties": { "Name": "Miami, FL", "description": "Miami, FL" }, "geometry": { "type": "Point", "coordinates": [ -80.299072, 25.799891 ] } },
{ "type": "Feature", "properties": { "Name": "Fort Lauderdale, FL", "description": "Fort Lauderdale, FL" }, "geometry": { "type": "Point", "coordinates": [ -80.145264, 26.056783 ] } },
{ "type": "Feature", "properties": { "Name": "Chattanooga, TN", "description": "Chattanooga, TN" }, "geometry": { "type": "Point", "coordinates": [ -85.220947, 35.074965 ] } },
{ "type": "Feature", "properties": { "Name": "Birmingham, AL", "description": "Birmingham, AL" }, "geometry": { "type": "Point", "coordinates": [ -86.572266, 33.559707 ] } },
{ "type": "Feature", "properties": { "Name": "Mobil, AL", "description": "Mobil, AL" }, "geometry": { "type": "Point", "coordinates": [ -88.066406, 30.732393 ] } },
{ "type": "Feature", "properties": { "Name": "Montgomery, AL", "description": "Montgomery, AL" }, "geometry": { "type": "Point", "coordinates": [ -86.088867, 32.379961 ] } },
{ "type": "Feature", "properties": { "Name": "Hattisburg, MS", "description": "Hattisburg, MS - University" }, "geometry": { "type": "Point", "coordinates": [ -89.230957, 31.400535 ] } },
{ "type": "Feature", "properties": { "Name": "Winston Salem, NC", "description": "Winston Salem, NC" }, "geometry": { "type": "Point", "coordinates": [ -80.211182, 36.120128 ] } },
{ "type": "Feature", "properties": { "Name": "Fayettville, NC", "description": "Fayettville, NC" }, "geometry": { "type": "Point", "coordinates": [ -78.815918, 35.083956 ] } },
{ "type": "Feature", "properties": { "Name": "Greenville, NC", "description": "Greenville, NC" }, "geometry": { "type": "Point", "coordinates": [ -77.332764, 35.603719 ] } },
{ "type": "Feature", "properties": { "Name": "Wilmington, NC", "description": "Wilmington, NC" }, "geometry": { "type": "Point", "coordinates": [ -77.915039, 34.243595 ] } },
{ "type": "Feature", "properties": { "Name": "Greenville, SC", "description": "Greenville, SC" }, "geometry": { "type": "Point", "coordinates": [ -82.32605, 34.795762 ] } },
{ "type": "Feature", "properties": { "Name": "Clemson, SC", "description": "Clemson, SC - University" }, "geometry": { "type": "Point", "coordinates": [ -82.823181, 34.679523 ] } },
{ "type": "Feature", "properties": { "Name": "Athens, GA", "description": "Athens, GA - University" }, "geometry": { "type": "Point", "coordinates": [ -83.388977, 33.95703 ] } },
{ "type": "Feature", "properties": { "Name": "Augusta, GA", "description": "Augusta, GA" }, "geometry": { "type": "Point", "coordinates": [ -81.936035, 33.532237 ] } },
{ "type": "Feature", "properties": { "Name": "Macon, GA", "description": "Macon, GA" }, "geometry": { "type": "Point", "coordinates": [ -83.605957, 32.87036 ] } },
{ "type": "Feature", "properties": { "Name": "Savannah, GA", "description": "Savannah, GA" }, "geometry": { "type": "Point", "coordinates": [ -81.068115, 32.119801 ] } },
{ "type": "Feature", "properties": { "Name": "Columbus, GA", "description": "Columbus, GA" }, "geometry": { "type": "Point", "coordinates": [ -84.924316, 32.481963 ] } },
{ "type": "Feature", "properties": { "Name": "PenSacola, FL", "description": "PenSacola, FL" }, "geometry": { "type": "Point", "coordinates": [ -87.242432, 30.477083 ] } },
{ "type": "Feature", "properties": { "Name": "Panama City, FL", "description": "Panama City, FL" }, "geometry": { "type": "Point", "coordinates": [ -85.649414, 30.192618 ] } },
{ "type": "Feature", "properties": { "Name": "Tallahausee, FL", "description": "Tallahausee, FL" }, "geometry": { "type": "Point", "coordinates": [ -84.177246, 30.448674 ] } },
{ "type": "Feature", "properties": { "Name": "Gainesville, FL", "description": "Gainesville, FL - University" }, "geometry": { "type": "Point", "coordinates": [ -82.287598, 29.64032 ] } },
{ "type": "Feature", "properties": { "Name": "Ocala, FL", "description": "Ocala, FL" }, "geometry": { "type": "Point", "coordinates": [ -82.089844, 29.190533 ] } },
{ "type": "Feature", "properties": { "Name": "Inverness, FL", "description": "Inverness, FL" }, "geometry": { "type": "Point", "coordinates": [ -82.298584, 28.854296 ] } },
{ "type": "Feature", "properties": { "Name": "Daytona, Beach, FL", "description": "Daytona, Beach, FL" }, "geometry": { "type": "Point", "coordinates": [ -81.00769, 29.190533 ] } },
{ "type": "Feature", "properties": { "Name": "Lakeland, FL", "description": "Lakeland, FL" }, "geometry": { "type": "Point", "coordinates": [ -81.908569, 28.052591 ] } },
{ "type": "Feature", "properties": { "Name": "Melbourne, FL", "description": "Melbourne, FL - University" }, "geometry": { "type": "Point", "coordinates": [ -80.634155, 28.052591 ] } },
{ "type": "Feature", "properties": { "Name": "Port ST. LUcie, FL", "description": "Port ST. LUcie, FL" }, "geometry": { "type": "Point", "coordinates": [ -80.293579, 27.274161 ] } },
{ "type": "Feature", "properties": { "Name": "West Palm Beach, FL", "description": "West Palm Beach, FL" }, "geometry": { "type": "Point", "coordinates": [ -80.079346, 26.725987 ] } },
{ "type": "Feature", "properties": { "Name": "Bradenton, FL", "description": "Bradenton, FL" }, "geometry": { "type": "Point", "coordinates": [ -82.562256, 27.444916 ] } },
{ "type": "Feature", "properties": { "Name": "Fort Mayers, FL", "description": "Fort Mayers, FL" }, "geometry": { "type": "Point", "coordinates": [ -81.831665, 26.652368 ] } },
{ "type": "Feature", "properties": { "Name": "Tuscaloosa,AL", "description": "University and community" }, "geometry": { "type": "Point", "coordinates": [ -87.561035, 33.073131 ] } },
{ "type": "Feature", "properties": { "Name": "Bozeman, MT", "description": "Bozeman, MT-University" }, "geometry": { "type": "Point", "coordinates": [ -111.027832, 45.706179 ] } },
{ "type": "Feature", "properties": { "Name": "Great Falls, MT", "description": "Great Falls, MT" }, "geometry": { "type": "Point", "coordinates": [ -111.247559, 47.532038 ] } },
{ "type": "Feature", "properties": { "Name": "Laramie, Wy", "description": "Laramie, Wy - University" }, "geometry": { "type": "Point", "coordinates": [ -105.5896, 41.26955 ] } },
{ "type": "Feature", "properties": { "Name": "Colorodo Spring, CO", "description": "Colorodo Spring, CO" }, "geometry": { "type": "Point", "coordinates": [ -104.82605, 38.852542 ] } },
{ "type": "Feature", "properties": { "Name": "Heighland Ranch, CO", "description": "Heighland Ranch, CO" }, "geometry": { "type": "Point", "coordinates": [ -104.952393, 39.499802 ] } },
{ "type": "Feature", "properties": { "Name": "Aurora, CO", "description": "Aurora, CO" }, "geometry": { "type": "Point", "coordinates": [ -104.82605, 39.736762 ] } },
{ "type": "Feature", "properties": { "Name": "Longmont, CO", "description": "Longmont, CO" }, "geometry": { "type": "Point", "coordinates": [ -105.095215, 40.14109 ] } },
{ "type": "Feature", "properties": { "Name": "Westminester, CO", "description": "Westminester, CO" }, "geometry": { "type": "Point", "coordinates": [ -105.012817, 39.834905 ] } },
{ "type": "Feature", "properties": { "Name": "Fort Collins, CO", "description": "Fort Collins, CO - University" }, "geometry": { "type": "Point", "coordinates": [ -104.996338, 40.580585 ] } },
{ "type": "Feature", "properties": { "Name": "Boulder, CO", "description": "Boulder, CO - University" }, "geometry": { "type": "Point", "coordinates": [ -105.281982, 39.985538 ] } },
{ "type": "Feature", "properties": { "Name": "Albuquerque, NM", "description": "Albuquerque, NM" }, "geometry": { "type": "Point", "coordinates": [ -106.589355, 35.083956 ] } },
{ "type": "Feature", "properties": { "Name": "Santa Fe, NM", "description": "Santa Fe, NM" }, "geometry": { "type": "Point", "coordinates": [ -105.88623, 35.764343 ] } },
{ "type": "Feature", "properties": { "Name": "Los Alamos, NM", "description": "Los Alamos, NM" }, "geometry": { "type": "Point", "coordinates": [ -106.303711, 35.924645 ] } },
{ "type": "Feature", "properties": { "Name": "Las Cruces, NM", "description": "Las Cruces, NM-University" }, "geometry": { "type": "Point", "coordinates": [ -106.677246, 32.305706 ] } },
{ "type": "Feature", "properties": { "Name": "Glendale, AZ", "description": "Glendale, AZ" }, "geometry": { "type": "Point", "coordinates": [ -112.192383, 33.527658 ] } },
{ "type": "Feature", "properties": { "Name": "Chandler, AZ", "description": "Chandler, AZ" }, "geometry": { "type": "Point", "coordinates": [ -111.796875, 33.298395 ] } },
{ "type": "Feature", "properties": { "Name": "Tempe, AZ", "description": "Tempe, AZ-University" }, "geometry": { "type": "Point", "coordinates": [ -111.936951, 33.415395 ] } },
{ "type": "Feature", "properties": { "Name": "Tucson, AZ", "description": "Tucson, AZ-University" }, "geometry": { "type": "Point", "coordinates": [ -110.88501, 32.23139 ] } },
{ "type": "Feature", "properties": { "Name": "Flagstaff, AZ", "description": "Flagstaff, AZ" }, "geometry": { "type": "Point", "coordinates": [ -111.588135, 35.218697 ] } },
{ "type": "Feature", "properties": { "Name": "Salt Lake city, UT", "description": "Salt Lake city, UT" }, "geometry": { "type": "Point", "coordinates": [ -111.796875, 40.730608 ] } },
{ "type": "Feature", "properties": { "Name": "Logan, UT", "description": "Logan, UT" }, "geometry": { "type": "Point", "coordinates": [ -111.829834, 41.763117 ] } },
{ "type": "Feature", "properties": { "Name": "Las Vegas, NV", "description": "Las Vegas, NV" }, "geometry": { "type": "Point", "coordinates": [ -115.026855, 36.120128 ] } },
{ "type": "Feature", "properties": { "Name": "Reno, NV", "description": "Reno, NV" }, "geometry": { "type": "Point", "coordinates": [ -119.707031, 39.571822 ] } },
{ "type": "Feature", "properties": { "Name": "Boise, ID", "description": "Boise, ID" }, "geometry": { "type": "Point", "coordinates": [ -116.147461, 43.628123 ] } },
{ "type": "Feature", "properties": { "Name": "Moscow, ID", "description": "Moscow, ID-University" }, "geometry": { "type": "Point", "coordinates": [ -117.004395, 46.664517 ] } },
{ "type": "Feature", "properties": { "Name": "Spokane, WA", "description": "Spokane, WA" }, "geometry": { "type": "Point", "coordinates": [ -117.37793, 47.687579 ] } },
{ "type": "Feature", "properties": { "Name": "Richland, WA", "description": "Richland, WA" }, "geometry": { "type": "Point", "coordinates": [ -119.190674, 46.259645 ] } },
{ "type": "Feature", "properties": { "Name": "Portland, OR", "description": "Portland, OR" }, "geometry": { "type": "Point", "coordinates": [ -122.662354, 45.506347 ] } },
{ "type": "Feature", "properties": { "Name": "Eugene, OR", "description": "Eugene, OR" }, "geometry": { "type": "Point", "coordinates": [ -123.057861, 44.056012 ] } },
{ "type": "Feature", "properties": { "Name": "Corvalis, OR", "description": "Corvalis, OR-University" }, "geometry": { "type": "Point", "coordinates": [ -123.189697, 44.566991 ] } },
{ "type": "Feature", "properties": { "Name": "Bakersfield, CA", "description": "Bakersfield, CA" }, "geometry": { "type": "Point", "coordinates": [ -118.981934, 35.38905 ] } },
{ "type": "Feature", "properties": { "Name": "Fresno, CA", "description": "Fresno, CA" }, "geometry": { "type": "Point", "coordinates": [ -119.750977, 36.70366 ] } },
{ "type": "Feature", "properties": { "Name": "Chico, CA", "description": "Chico, CA" }, "geometry": { "type": "Point", "coordinates": [ -121.827393, 39.698734 ] } },
{ "type": "Feature", "properties": { "Name": "Santa Barbara, CA", "description": "Santa Barbara, CA" }, "geometry": { "type": "Point", "coordinates": [ -119.674072, 34.452218 ] } },
{ "type": "Feature", "properties": { "Name": "Alaska", "description": "Alaska" }, "geometry": { "type": "Point", "coordinates": [ -154.160156, 62.349609 ] } },
{ "type": "Feature", "properties": { "Name": "Hawai", "description": "Hawai" }, "geometry": { "type": "Point", "coordinates": [ -155.43457, 19.68397 ] } },
{ "type": "Feature", "properties": { "Name": "Sugarland, TX", "description": "Sugarland, TX" }, "geometry": { "type": "Point", "coordinates": [ -95.627747, 29.645095 ] } },
{ "type": "Feature", "properties": { "Name": "Pearland, TX", "description": "Pearland, TX" }, "geometry": { "type": "Point", "coordinates": [ -95.281677, 29.578234 ] } },
{ "type": "Feature", "properties": { "Name": "Jersey Village, TX", "description": "Jersey Village, TX" }, "geometry": { "type": "Point", "coordinates": [ -95.589294, 29.957314 ] } },
{ "type": "Feature", "properties": { "Name": "San Antonio, TX", "description": "San Antonio, TX" }, "geometry": { "type": "Point", "coordinates": [ -98.492432, 29.430029 ] } },
{ "type": "Feature", "properties": { "Name": "Austin, TX", "description": "Austin, TX" }, "geometry": { "type": "Point", "coordinates": [ -97.745361, 30.287532 ] } },
{ "type": "Feature", "properties": { "Name": "Arlington, TX", "description": "Arlington, TX" }, "geometry": { "type": "Point", "coordinates": [ -97.088928, 32.7018 ] } },
{ "type": "Feature", "properties": { "Name": "Irving, TX", "description": "Irving, TX" }, "geometry": { "type": "Point", "coordinates": [ -96.957092, 32.872667 ] } },
{ "type": "Feature", "properties": { "Name": "Plano, TX", "description": "Plano, TX" }, "geometry": { "type": "Point", "coordinates": [ -96.729126, 32.992539 ] } },
{ "type": "Feature", "properties": { "Name": "Tulsa, OK", "description": "Tulsa, OK" }, "geometry": { "type": "Point", "coordinates": [ -95.921631, 36.191092 ] } },
{ "type": "Feature", "properties": { "Name": "Stillwater, OK", "description": "Stillwater, OK-University" }, "geometry": { "type": "Point", "coordinates": [ -96.987305, 36.155618 ] } },
{ "type": "Feature", "properties": { "Name": "Oklahoma City, OK", "description": "Oklahoma City, OK" }, "geometry": { "type": "Point", "coordinates": [ -97.470703, 35.478565 ] } },
{ "type": "Feature", "properties": { "Name": "Norman, OK", "description": "Norman, OK-University" }, "geometry": { "type": "Point", "coordinates": [ -102.480469, 35.746512 ] } },
{ "type": "Feature", "properties": { "Name": "St. Louis, MO", "description": "St. Louis, MO" }, "geometry": { "type": "Point", "coordinates": [ -90.318604, 38.642618 ] } },
{ "type": "Feature", "properties": { "Name": "Rolla, MO", "description": "Rolla, MO-University" }, "geometry": { "type": "Point", "coordinates": [ -91.746826, 37.970185 ] } },
{ "type": "Feature", "properties": { "Name": "Overland park, KS", "description": "Overland park, KS" }, "geometry": { "type": "Point", "coordinates": [ -94.724121, 38.985033 ] } },
{ "type": "Feature", "properties": { "Name": "Wichita, KS", "description": "Wichita, KS-University" }, "geometry": { "type": "Point", "coordinates": [ -97.272949, 37.701207 ] } },
{ "type": "Feature", "properties": { "Name": "Manhattan, KS", "description": "Manhattan, KS-University" }, "geometry": { "type": "Point", "coordinates": [ -96.536865, 39.172659 ] } },
{ "type": "Feature", "properties": { "Name": "Lawrence, KS", "description": "Lawrence, KS-University" }, "geometry": { "type": "Point", "coordinates": [ -95.218506, 38.967951 ] } },
{ "type": "Feature", "properties": { "Name": "Lincoln, NE", "description": "Lincoln, NE-University" }, "geometry": { "type": "Point", "coordinates": [ -96.668701, 40.830437 ] } },
{ "type": "Feature", "properties": { "Name": "Omaha, NE", "description": "Omaha, NE" }, "geometry": { "type": "Point", "coordinates": [ -96.015015, 41.261291 ] } },
{ "type": "Feature", "properties": { "Name": "Sioux Falls, SD", "description": "Sioux Falls, SD" }, "geometry": { "type": "Point", "coordinates": [ -96.740112, 43.572432 ] } },
{ "type": "Feature", "properties": { "Name": "BrooKings, SD", "description": "BrooKings, SD-University" }, "geometry": { "type": "Point", "coordinates": [ -96.756592, 44.308127 ] } },
{ "type": "Feature", "properties": { "Name": "Fargo, ND", "description": "Fargo, ND-University" }, "geometry": { "type": "Point", "coordinates": [ -96.800537, 46.893985 ] } },
{ "type": "Feature", "properties": { "Name": "Eagan, MN", "description": "Eagan, MN" }, "geometry": { "type": "Point", "coordinates": [ -93.249207, 44.818864 ] } },
{ "type": "Feature", "properties": { "Name": "Edina, MN", "description": "Edina, MN" }, "geometry": { "type": "Point", "coordinates": [ -93.435974, 44.881174 ] } },
{ "type": "Feature", "properties": { "Name": "St. Paul, MN", "description": "St. Paul, MN" }, "geometry": { "type": "Point", "coordinates": [ -93.048706, 44.972571 ] } },
{ "type": "Feature", "properties": { "Name": "Brooklyne park, MN", "description": "Brooklyne park, MN" }, "geometry": { "type": "Point", "coordinates": [ -93.372803, 45.073521 ] } },
{ "type": "Feature", "properties": { "Name": "Minneapolis, MN", "description": "Minneapolis, MN-University" }, "geometry": { "type": "Point", "coordinates": [ -93.257446, 44.982285 ] } },
{ "type": "Feature", "properties": { "Name": "Rochester, MN", "description": "Rochester, MN" }, "geometry": { "type": "Point", "coordinates": [ -92.460937, 44.018496 ] } },
{ "type": "Feature", "properties": { "Name": "Ames, IA", "description": "Ames, IA-University" }, "geometry": { "type": "Point", "coordinates": [ -93.630981, 42.065607 ] } },
{ "type": "Feature", "properties": { "Name": "Waterloo, IA", "description": "Waterloo, IA" }, "geometry": { "type": "Point", "coordinates": [ -92.37854, 42.512602 ] } },
{ "type": "Feature", "properties": { "Name": "Iowa City, IA", "description": "Iowa City, IA-University" }, "geometry": { "type": "Point", "coordinates": [ -91.549072, 41.668809 ] } },
{ "type": "Feature", "properties": { "Name": "Cedar Rapids, IA", "description": "Cedar Rapids, IA" }, "geometry": { "type": "Point", "coordinates": [ -91.658936, 41.926803 ] } },
{ "type": "Feature", "properties": { "Name": "Des Moines, IA", "description": "Des Moines, IA" }, "geometry": { "type": "Point", "coordinates": [ -93.554077, 41.611335 ] } },
{ "type": "Feature", "properties": { "Name": "Fairfield (Vedic City), IA", "description": "Fairfield (Vedic City), IA" }, "geometry": { "type": "Point", "coordinates": [ -91.94458, 41.008921 ] } },
{ "type": "Feature", "properties": { "Name": "Houghton, MI", "description": "Houghton, MI-University" }, "geometry": { "type": "Point", "coordinates": [ -88.527832, 47.137425 ] } },
{ "type": "Feature", "properties": { "Name": "Midland, MI", "description": "Midland, MI" }, "geometry": { "type": "Point", "coordinates": [ -84.089355, 43.55651 ] } },
{ "type": "Feature", "properties": { "Name": "Flint, MI", "description": "Flint, MI" }, "geometry": { "type": "Point", "coordinates": [ -83.671875, 43.004647 ] } },
{ "type": "Feature", "properties": { "Name": "Lansing, MI", "description": "Lansing, MI" }, "geometry": { "type": "Point", "coordinates": [ -84.506836, 42.738944 ] } },
{ "type": "Feature", "properties": { "Name": "Grand Rapids, MI", "description": "Grand Rapids, MI" }, "geometry": { "type": "Point", "coordinates": [ -85.627441, 42.98054 ] } },
{ "type": "Feature", "properties": { "Name": "Kalamazoo, MI", "description": "Kalamazoo, MI" }, "geometry": { "type": "Point", "coordinates": [ -85.583496, 42.269179 ] } },
{ "type": "Feature", "properties": { "Name": "Ann Arbor, MI", "description": "Ann Arbor, MI-University" }, "geometry": { "type": "Point", "coordinates": [ -83.704834, 42.277309 ] } },
{ "type": "Feature", "properties": { "Name": "Benton Harbor, MI", "description": "Benton Harbor, MI" }, "geometry": { "type": "Point", "coordinates": [ -86.418457, 42.118599 ] } },
{ "type": "Feature", "properties": { "Name": "Canton, MI", "description": "Canton, MI" }, "geometry": { "type": "Point", "coordinates": [ -83.474121, 42.31997 ] } },
{ "type": "Feature", "properties": { "Name": "Farmington Hills, MI", "description": "Farmington Hills, MI" }, "geometry": { "type": "Point", "coordinates": [ -83.438416, 42.4802 ] } },
{ "type": "Feature", "properties": { "Name": "Troy, MI", "description": "Troy, MI" }, "geometry": { "type": "Point", "coordinates": [ -83.16925, 42.617791 ] } },
{ "type": "Feature", "properties": { "Name": "Detroit, MI", "description": "Detroit, MI-University" }, "geometry": { "type": "Point", "coordinates": [ -83.06488, 42.368691 ] } },
{ "type": "Feature", "properties": { "Name": "Dubuque, IA", "description": "Dubuque, IA" }, "geometry": { "type": "Point", "coordinates": [ -90.615234, 42.5207 ] } },
{ "type": "Feature", "properties": { "Name": "Fort Wayne, IN", "description": "Fort Wayne, IN" }, "geometry": { "type": "Point", "coordinates": [ -85.067139, 41.087632 ] } },
{ "type": "Feature", "properties": { "Name": "Lafayette, IN", "description": "Lafayette, IN-University" }, "geometry": { "type": "Point", "coordinates": [ -86.912842, 40.455307 ] } },
{ "type": "Feature", "properties": { "Name": "Carmel, IN", "description": "Carmel, IN" }, "geometry": { "type": "Point", "coordinates": [ -86.088867, 39.943436 ] } },
{ "type": "Feature", "properties": { "Name": "Bloomington, IN", "description": "Bloomington, IN-University" }, "geometry": { "type": "Point", "coordinates": [ -86.522827, 39.185433 ] } },
{ "type": "Feature", "properties": { "Name": "Columbus, IN", "description": "Columbus, IN" }, "geometry": { "type": "Point", "coordinates": [ -85.880127, 39.202462 ] } },
{ "type": "Feature", "properties": { "Name": "Louisville, KY", "description": "Louisville, KY" }, "geometry": { "type": "Point", "coordinates": [ -85.6604, 38.233865 ] } },
{ "type": "Feature", "properties": { "Name": "Lexington, KY", "description": "Lexington, KY-University" }, "geometry": { "type": "Point", "coordinates": [ -84.484863, 38.043765 ] } },
{ "type": "Feature", "properties": { "Name": "Bowling Green, KY", "description": "Bowling Green, KY-University" }, "geometry": { "type": "Point", "coordinates": [ -86.401978, 36.993778 ] } },
{ "type": "Feature", "properties": { "Name": "Cincinnati, OH", "description": "Cincinnati, OH-University" }, "geometry": { "type": "Point", "coordinates": [ -84.47937, 39.117276 ] } },
{ "type": "Feature", "properties": { "Name": "West Chester, OH", "description": "West Chester, OH" }, "geometry": { "type": "Point", "coordinates": [ -84.361267, 39.338546 ] } },
{ "type": "Feature", "properties": { "Name": "Dayton, OH", "description": "Dayton, OH" }, "geometry": { "type": "Point", "coordinates": [ -84.1745, 39.721976 ] } },
{ "type": "Feature", "properties": { "Name": "Toledo, OH", "description": "Toledo, OH" }, "geometry": { "type": "Point", "coordinates": [ -83.597717, 41.642131 ] } },
{ "type": "Feature", "properties": { "Name": "Dublin, OH", "description": "Dublin, OH" }, "geometry": { "type": "Point", "coordinates": [ -83.136292, 40.12009 ] } },
{ "type": "Feature", "properties": { "Name": "Westerville, OH", "description": "Westerville, OH" }, "geometry": { "type": "Point", "coordinates": [ -82.935791, 40.124291 ] } },
{ "type": "Feature", "properties": { "Name": "Columbus, OH", "description": "Columbus, OH-University" }, "geometry": { "type": "Point", "coordinates": [ -82.963257, 39.958175 ] } },
{ "type": "Feature", "properties": { "Name": "Athens, OH", "description": "Athens, OH-University" }, "geometry": { "type": "Point", "coordinates": [ -82.089844, 39.32155 ] } },
{ "type": "Feature", "properties": { "Name": "Akron, OH", "description": "Akron, OH" }, "geometry": { "type": "Point", "coordinates": [ -81.546021, 41.083492 ] } },
{ "type": "Feature", "properties": { "Name": "Warren, OH", "description": "Warren, OH" }, "geometry": { "type": "Point", "coordinates": [ -80.689087, 41.129021 ] } },
{ "type": "Feature", "properties": { "Name": "Solon, OH", "description": "Solon, OH" }, "geometry": { "type": "Point", "coordinates": [ -81.448517, 41.395355 ] } },
{ "type": "Feature", "properties": { "Name": "Middlesburg Height, OH", "description": "Middlesburg Height, OH" }, "geometry": { "type": "Point", "coordinates": [ -81.812439, 41.363411 ] } },
{ "type": "Feature", "properties": { "Name": "Cleveland, OH", "description": "Cleveland, OH" }, "geometry": { "type": "Point", "coordinates": [ -81.673737, 41.489035 ] } },
{ "type": "Feature", "properties": { "Name": "Temple, TX", "description": "Temple, TX" }, "geometry": { "type": "Point", "coordinates": [ -97.327881, 31.128199 ] } },
{ "type": "Feature", "properties": { "Name": "Bentonville, AR", "description": "Bentonville, AR" }, "geometry": { "type": "Point", "coordinates": [ -94.174805, 36.354951 ] } },
{ "type": "Feature", "properties": { "Name": "Fayeteville, AR", "description": "Fayeteville, AR" }, "geometry": { "type": "Point", "coordinates": [ -94.147339, 36.08906 ] } },
{ "type": "Feature", "properties": { "Name": "Olympia, WA", "description": "Olympia, WA" }, "geometry": { "type": "Point", "coordinates": [ -122.860107, 47.032695 ] } },
{ "type": "Feature", "properties": { "Name": "Lakewood, WA", "description": "Lakewood, WA" }, "geometry": { "type": "Point", "coordinates": [ -122.437134, 47.171044 ] } },
{ "type": "Feature", "properties": { "Name": "Seattle, WA", "description": "Seattle, WA-University" }, "geometry": { "type": "Point", "coordinates": [ -122.316284, 47.598755 ] } },
{ "type": "Feature", "properties": { "Name": "Bellevue, WA", "description": "Bellevue, WA" }, "geometry": { "type": "Point", "coordinates": [ -122.156982, 47.580231 ] } },
{ "type": "Feature", "properties": { "Name": "Lynnwood, WA", "description": "Lynnwood, WA" }, "geometry": { "type": "Point", "coordinates": [ -122.272339, 47.835283 ] } },
{ "type": "Feature", "properties": { "Name": "Sacramento 1, CA", "description": "Sacramento 1, CA" }, "geometry": { "type": "Point", "coordinates": [ -121.530762, 38.651198 ] } },
{ "type": "Feature", "properties": { "Name": "Sacramento 2, CA", "description": "Sacramento 2, CA" }, "geometry": { "type": "Point", "coordinates": [ -121.387939, 38.522384 ] } },
{ "type": "Feature", "properties": { "Name": "Stockton, CA", "description": "Stockton, CA" }, "geometry": { "type": "Point", "coordinates": [ -121.261597, 37.939865 ] } },
{ "type": "Feature", "properties": { "Name": "Tracy, CA", "description": "Tracy, CA" }, "geometry": { "type": "Point", "coordinates": [ -121.398926, 37.753344 ] } },
{ "type": "Feature", "properties": { "Name": "Vallejo, CA", "description": "Vallejo, CA" }, "geometry": { "type": "Point", "coordinates": [ -122.236633, 38.108628 ] } },
{ "type": "Feature", "properties": { "Name": "Richmond, CA", "description": "Richmond, CA" }, "geometry": { "type": "Point", "coordinates": [ -122.310791, 37.946363 ] } },
{ "type": "Feature", "properties": { "Name": "Concord, CA", "description": "Concord, CA" }, "geometry": { "type": "Point", "coordinates": [ -122.052612, 37.98534 ] } },
{ "type": "Feature", "properties": { "Name": "San Francisco, CA", "description": "San Francisco, CA" }, "geometry": { "type": "Point", "coordinates": [ -122.445374, 37.740313 ] } },
{ "type": "Feature", "properties": { "Name": "Alameda, CA", "description": "Alameda, CA" }, "geometry": { "type": "Point", "coordinates": [ -122.203674, 37.78374 ] } },
{ "type": "Feature", "properties": { "Name": "San Ramon, CA", "description": "San Ramon, CA" }, "geometry": { "type": "Point", "coordinates": [ -121.934509, 37.757687 ] } },
{ "type": "Feature", "properties": { "Name": "Union City, CA", "description": "Union City, CA" }, "geometry": { "type": "Point", "coordinates": [ -122.071838, 37.605528 ] } },
{ "type": "Feature", "properties": { "Name": "Freemont, CA", "description": "Freemont, CA" }, "geometry": { "type": "Point", "coordinates": [ -121.967468, 37.538044 ] } },
{ "type": "Feature", "properties": { "Name": "San Jose, CA", "description": "San Jose, CA" }, "geometry": { "type": "Point", "coordinates": [ -121.849365, 37.319936 ] } },
{ "type": "Feature", "properties": { "Name": "Sunnyvale, CA", "description": "Sunnyvale, CA" }, "geometry": { "type": "Point", "coordinates": [ -122.0224, 37.378888 ] } },
{ "type": "Feature", "properties": { "Name": "Cupertino, CA", "description": "Cupertino, CA" }, "geometry": { "type": "Point", "coordinates": [ -122.0224, 37.32212 ] } },
{ "type": "Feature", "properties": { "Name": "San Mateo, CA", "description": "San Mateo, CA" }, "geometry": { "type": "Point", "coordinates": [ -122.295685, 37.543488 ] } },
{ "type": "Feature", "properties": { "Name": "Santa Cruz, CA", "description": "Santa Cruz, CA" }, "geometry": { "type": "Point", "coordinates": [ -122.008667, 36.982809 ] } },
{ "type": "Feature", "properties": { "Name": "Morgan Hill, CA", "description": "Morgan Hill, CA" }, "geometry": { "type": "Point", "coordinates": [ -121.644745, 37.139519 ] } },
{ "type": "Feature", "properties": { "Name": "Gilroy, CA", "description": "Gilroy, CA" }, "geometry": { "type": "Point", "coordinates": [ -121.581573, 37.020098 ] } },
{ "type": "Feature", "properties": { "Name": "Merced, CA", "description": "Merced, CA" }, "geometry": { "type": "Point", "coordinates": [ -120.52002, 37.304645 ] } },
{ "type": "Feature", "properties": { "Name": "Marina, CA", "description": "Marina, CA" }, "geometry": { "type": "Point", "coordinates": [ -121.794434, 36.690446 ] } },
{ "type": "Feature", "properties": { "Name": "San Diego, CA", "description": "San Diego, CA" }, "geometry": { "type": "Point", "coordinates": [ -117.037354, 32.639375 ] } },
{ "type": "Feature", "properties": { "Name": "La Jola, CA", "description": "La Jola, CA" }, "geometry": { "type": "Point", "coordinates": [ -117.169189, 32.833443 ] } },
{ "type": "Feature", "properties": { "Name": "Thousand Oaks, CA", "description": "Thousand Oaks, CA" }, "geometry": { "type": "Point", "coordinates": [ -118.795166, 34.161818 ] } },
{ "type": "Feature", "properties": { "Name": "Simi Valley, CA", "description": "Simi Valley, CA" }, "geometry": { "type": "Point", "coordinates": [ -118.688049, 34.270836 ] } },
{ "type": "Feature", "properties": { "Name": "Los Angeles, CA", "description": "Los Angeles, CA" }, "geometry": { "type": "Point", "coordinates": [ -118.265076, 34.056073 ] } },
{ "type": "Feature", "properties": { "Name": "Pasadena, CA", "description": "Pasadena, CA" }, "geometry": { "type": "Point", "coordinates": [ -118.153839, 34.126584 ] } },
{ "type": "Feature", "properties": { "Name": "WalNUT, CA", "description": "WalNUT, CA" }, "geometry": { "type": "Point", "coordinates": [ -117.826996, 34.01055 ] } },
{ "type": "Feature", "properties": { "Name": "Riverside, CA", "description": "Riverside, CA" }, "geometry": { "type": "Point", "coordinates": [ -117.36969, 33.970698 ] } },
{ "type": "Feature", "properties": { "Name": "Torrance, CA", "description": "Torrance, CA" }, "geometry": { "type": "Point", "coordinates": [ -118.303528, 33.82023 ] } },
{ "type": "Feature", "properties": { "Name": "Cerritos, CA", "description": "Cerritos, CA" }, "geometry": { "type": "Point", "coordinates": [ -118.054962, 33.854451 ] } },
{ "type": "Feature", "properties": { "Name": "Westminister, CA", "description": "Westminister, CA" }, "geometry": { "type": "Point", "coordinates": [ -117.970505, 33.742042 ] } },
{ "type": "Feature", "properties": { "Name": "Irvine, CA", "description": "Irvine, CA" }, "geometry": { "type": "Point", "coordinates": [ -117.790604, 33.676926 ] } },
{ "type": "Feature", "properties": { "Name": "Morrow, GA", "description": "Morrow, GA" }, "geometry": { "type": "Point", "coordinates": [ -84.348907, 33.602038 ] } },
{ "type": "Feature", "properties": { "Name": "Atlanta, GA", "description": "Atlanta, GA" }, "geometry": { "type": "Point", "coordinates": [ -84.385986, 33.754031 ] } },
{ "type": "Feature", "properties": { "Name": "Decatur, GA", "description": "Decatur, GA" }, "geometry": { "type": "Point", "coordinates": [ -84.26651, 33.793985 ] } },
{ "type": "Feature", "properties": { "Name": "Smyma, GA", "description": "Smyma, GA" }, "geometry": { "type": "Point", "coordinates": [ -84.472504, 33.892077 ] } },
{ "type": "Feature", "properties": { "Name": "Marietta, GA", "description": "Marietta, GA" }, "geometry": { "type": "Point", "coordinates": [ -84.550781, 33.983225 ] } },
{ "type": "Feature", "properties": { "Name": "Sandy Spring, GA", "description": "Sandy Spring, GA" }, "geometry": { "type": "Point", "coordinates": [ -84.359894, 33.922851 ] } },
{ "type": "Feature", "properties": { "Name": "Duluth, GA", "description": "Duluth, GA" }, "geometry": { "type": "Point", "coordinates": [ -84.14566, 33.98778 ] } },
{ "type": "Feature", "properties": { "Name": "Alpharetta, GA", "description": "Alpharetta, GA" }, "geometry": { "type": "Point", "coordinates": [ -84.25827, 34.057211 ] } },
{ "type": "Feature", "properties": { "Name": "Fairfax, VA", "description": "Fairfax, VA" }, "geometry": { "type": "Point", "coordinates": [ -77.33551, 38.863236 ] } },
{ "type": "Feature", "properties": { "Name": "Springfield, VA", "description": "Springfield, VA" }, "geometry": { "type": "Point", "coordinates": [ -77.203674, 38.758367 ] } },
{ "type": "Feature", "properties": { "Name": "Sterling, VA", "description": "Sterling, VA" }, "geometry": { "type": "Point", "coordinates": [ -77.412415, 38.97329 ] } },
{ "type": "Feature", "properties": { "Name": "Rockville, MD", "description": "Rockville, MD" }, "geometry": { "type": "Point", "coordinates": [ -77.183075, 39.0917 ] } },
{ "type": "Feature", "properties": { "Name": "Columbia, MD", "description": "Columbia, MD" }, "geometry": { "type": "Point", "coordinates": [ -76.854858, 39.224807 ] } },
{ "type": "Feature", "properties": { "Name": "Gainesville, VA", "description": "Gainesville, VA" }, "geometry": { "type": "Point", "coordinates": [ -77.519531, 38.796908 ] } },
{ "type": "Feature", "properties": { "Name": "Ijamsville, MD", "description": "Ijamsville, MD" }, "geometry": { "type": "Point", "coordinates": [ -77.357483, 39.349166 ] } },
{ "type": "Feature", "properties": { "Name": "Towson, MD", "description": "Towson, MD" }, "geometry": { "type": "Point", "coordinates": [ -76.615906, 39.43195 ] } },
{ "type": "Feature", "properties": { "Name": "Nottingham, MD", "description": "Nottingham, MD" }, "geometry": { "type": "Point", "coordinates": [ -76.489563, 39.381018 ] } },
{ "type": "Feature", "properties": { "Name": "Blacksburg, VA", "description": "Blacksburg, VA-University" }, "geometry": { "type": "Point", "coordinates": [ -80.386963, 37.217206 ] } },
{ "type": "Feature", "properties": { "Name": "Richmond, VA", "description": "Richmond, VA" }, "geometry": { "type": "Point", "coordinates": [ -77.387695, 37.509726 ] } },
{ "type": "Feature", "properties": { "Name": "Charlottsville, VA", "description": "Charlottsville, VA" }, "geometry": { "type": "Point", "coordinates": [ -78.442383, 38.048091 ] } },
{ "type": "Feature", "properties": { "Name": "Norfolk, VA", "description": "Norfolk, VA" }, "geometry": { "type": "Point", "coordinates": [ -76.256104, 36.848857 ] } },
{ "type": "Feature", "properties": { "Name": "Morgantown, WV", "description": "Morgantown, WV" }, "geometry": { "type": "Point", "coordinates": [ -79.920044, 39.639538 ] } },
{ "type": "Feature", "properties": { "Name": "Newark, DE", "description": "Newark, DE" }, "geometry": { "type": "Point", "coordinates": [ -75.679321, 39.690281 ] } },
{ "type": "Feature", "properties": { "Name": "Erie, PA", "description": "Erie, PA" }, "geometry": { "type": "Point", "coordinates": [ -80.062866, 42.085994 ] } },
{ "type": "Feature", "properties": { "Name": "Pittsburgh, PA", "description": "Pittsburgh, PA" }, "geometry": { "type": "Point", "coordinates": [ -79.94751, 40.467845 ] } },
{ "type": "Feature", "properties": { "Name": "State College, PA", "description": "State College, PA-University" }, "geometry": { "type": "Point", "coordinates": [ -77.832642, 40.805494 ] } },
{ "type": "Feature", "properties": { "Name": "Harrisburg, PA", "description": "Harrisburg, PA" }, "geometry": { "type": "Point", "coordinates": [ -76.799927, 40.237605 ] } },
{ "type": "Feature", "properties": { "Name": "Exton, PA", "description": "Exton, PA" }, "geometry": { "type": "Point", "coordinates": [ -75.618896, 40.010787 ] } },
{ "type": "Feature", "properties": { "Name": "Norristown, PA", "description": "Norristown, PA" }, "geometry": { "type": "Point", "coordinates": [ -75.352478, 40.086477 ] } },
{ "type": "Feature", "properties": { "Name": "Lansdale, PA", "description": "Lansdale, PA" }, "geometry": { "type": "Point", "coordinates": [ -75.253601, 40.227121 ] } },
{ "type": "Feature", "properties": { "Name": "Philadelphia, PA", "description": "Philadelphia, PA" }, "geometry": { "type": "Point", "coordinates": [ -75.149231, 39.932907 ] } },
{ "type": "Feature", "properties": { "Name": "Cherry Hills, NJ", "description": "Cherry Hills, NJ" }, "geometry": { "type": "Point", "coordinates": [ -75.000916, 39.861263 ] } },
{ "type": "Feature", "properties": { "Name": "Atlantic City, NJ", "description": "Atlantic City, NJ" }, "geometry": { "type": "Point", "coordinates": [ -74.542236, 39.383141 ] } },
{ "type": "Feature", "properties": { "Name": "Scranton, PA", "description": "Scranton, PA" }, "geometry": { "type": "Point", "coordinates": [ -75.629883, 41.401536 ] } },
{ "type": "Feature", "properties": { "Name": "Bordentown Township, NJ", "description": "Bordentown Township, NJ" }, "geometry": { "type": "Point", "coordinates": [ -74.689178, 40.146339 ] } },
{ "type": "Feature", "properties": { "Name": "South Brunswick Township, NJ", "description": "South Brunswick Township, NJ" }, "geometry": { "type": "Point", "coordinates": [ -74.502411, 40.341311 ] } },
{ "type": "Feature", "properties": { "Name": "Malboro, NJ", "description": "Malboro, NJ" }, "geometry": { "type": "Point", "coordinates": [ -74.251099, 40.369043 ] } },
{ "type": "Feature", "properties": { "Name": "Edison, NJ", "description": "Edison, NJ" }, "geometry": { "type": "Point", "coordinates": [ -74.384308, 40.516409 ] } },
{ "type": "Feature", "properties": { "Name": "Somerville, NJ", "description": "Somerville, NJ" }, "geometry": { "type": "Point", "coordinates": [ -74.593735, 40.575891 ] } },
{ "type": "Feature", "properties": { "Name": "Staten Island, NY", "description": "Staten Island, NY" }, "geometry": { "type": "Point", "coordinates": [ -74.148102, 40.568589 ] } },
{ "type": "Feature", "properties": { "Name": "Woodbridge Township, NJ", "description": "Woodbridge Township, NJ" }, "geometry": { "type": "Point", "coordinates": [ -74.297104, 40.552418 ] } },
{ "type": "Feature", "properties": { "Name": "Parsippeney, NJ", "description": "Parsippeney, NJ" }, "geometry": { "type": "Point", "coordinates": [ -74.409027, 40.855371 ] } },
{ "type": "Feature", "properties": { "Name": "Stanhope, NJ", "description": "Stanhope, NJ" }, "geometry": { "type": "Point", "coordinates": [ -74.698792, 40.896906 ] } },
{ "type": "Feature", "properties": { "Name": "Paramus, NJ", "description": "Paramus, NJ" }, "geometry": { "type": "Point", "coordinates": [ -74.071198, 40.925965 ] } },
{ "type": "Feature", "properties": { "Name": "Jersey City, NJ", "description": "Jersey City, NJ" }, "geometry": { "type": "Point", "coordinates": [ -74.060211, 40.721762 ] } },
{ "type": "Feature", "properties": { "Name": "Fort Lee, NJ", "description": "Fort Lee, NJ" }, "geometry": { "type": "Point", "coordinates": [ -73.98056, 40.841866 ] } },
{ "type": "Feature", "properties": { "Name": "Buffalo, NY", "description": "Buffalo, NY" }, "geometry": { "type": "Point", "coordinates": [ -78.771973, 42.843751 ] } },
{ "type": "Feature", "properties": { "Name": "Rochester, NY", "description": "Rochester, NY" }, "geometry": { "type": "Point", "coordinates": [ -77.563477, 43.125043 ] } },
{ "type": "Feature", "properties": { "Name": "Syracuse, NY", "description": "Syracuse, NY" }, "geometry": { "type": "Point", "coordinates": [ -76.080322, 43.036776 ] } },
{ "type": "Feature", "properties": { "Name": "Utica, NY", "description": "Utica, NY" }, "geometry": { "type": "Point", "coordinates": [ -75.19043, 43.109004 ] } },
{ "type": "Feature", "properties": { "Name": "Ithaca, NY", "description": "Ithaca, NY-University" }, "geometry": { "type": "Point", "coordinates": [ -76.442871, 42.423457 ] } },
{ "type": "Feature", "properties": { "Name": "Albany, NY", "description": "Albany, NY" }, "geometry": { "type": "Point", "coordinates": [ -73.773193, 42.674359 ] } },
{ "type": "Feature", "properties": { "Name": "Binghamton, NY", "description": "Binghamton, NY" }, "geometry": { "type": "Point", "coordinates": [ -75.860596, 42.122673 ] } },
{ "type": "Feature", "properties": { "Name": "Newburgh, NY", "description": "Newburgh, NY" }, "geometry": { "type": "Point", "coordinates": [ -74.025879, 41.570252 ] } },
{ "type": "Feature", "properties": { "Name": "New City, NY", "description": "New City, NY" }, "geometry": { "type": "Point", "coordinates": [ -73.979187, 41.126953 ] } },
{ "type": "Feature", "properties": { "Name": "White Planes, NY", "description": "White Planes, NY" }, "geometry": { "type": "Point", "coordinates": [ -73.791046, 41.026535 ] } },
{ "type": "Feature", "properties": { "Name": "New York, NY", "description": "New York, NY" }, "geometry": { "type": "Point", "coordinates": [ -73.977814, 40.753499 ] } },
{ "type": "Feature", "properties": { "Name": "Queens, NY", "description": "Queens, NY" }, "geometry": { "type": "Point", "coordinates": [ -73.799286, 40.746217 ] } },
{ "type": "Feature", "properties": { "Name": "Brooklyn, NY", "description": "Brooklyn, NY" }, "geometry": { "type": "Point", "coordinates": [ -73.947601, 40.659806 ] } },
{ "type": "Feature", "properties": { "Name": "Hicksville, NY", "description": "Hicksville, NY" }, "geometry": { "type": "Point", "coordinates": [ -73.528748, 40.773262 ] } },
{ "type": "Feature", "properties": { "Name": "East Setauket, NY", "description": "East Setauket, NY" }, "geometry": { "type": "Point", "coordinates": [ -73.109207, 40.90988 ] } },
{ "type": "Feature", "properties": { "Name": "New Orleans,LA", "description": "New Orleans,LA" }, "geometry": { "type": "Point", "coordinates": [ -90.071411, 29.945415 ] } },
{ "type": "Feature", "properties": { "Name": "Baton Rouge,LA", "description": "Baton Rouge,LA" }, "geometry": { "type": "Point", "coordinates": [ -91.157684, 30.446306 ] } },
{ "type": "Feature", "properties": { "Name": "Lafayette,LA", "description": "Lafayette,LA" }, "geometry": { "type": "Point", "coordinates": [ -92.014618, 30.246018 ] } },
{ "type": "Feature", "properties": { "Name": "Danbury, CT", "description": "Danbury, CT" }, "geometry": { "type": "Point", "coordinates": [ -73.432617, 41.418015 ] } },
{ "type": "Feature", "properties": { "Name": "Stamford, CT", "description": "Stamford, CT" }, "geometry": { "type": "Point", "coordinates": [ -73.45459, 41.083492 ] } },
{ "type": "Feature", "properties": { "Name": "New Haven, CT", "description": "New Haven, CT" }, "geometry": { "type": "Point", "coordinates": [ -72.932739, 41.302571 ] } },
{ "type": "Feature", "properties": { "Name": "Manchester, CT", "description": "Manchester, CT" }, "geometry": { "type": "Point", "coordinates": [ -72.493286, 41.804078 ] } },
{ "type": "Feature", "properties": { "Name": "Hartford, CT", "description": "Hartford, CT" }, "geometry": { "type": "Point", "coordinates": [ -72.740479, 41.767215 ] } },
{ "type": "Feature", "properties": { "Name": "Norwich, CT", "description": "Norwich, CT" }, "geometry": { "type": "Point", "coordinates": [ -72.097778, 41.492121 ] } },
{ "type": "Feature", "properties": { "Name": "Hanover, VT", "description": "Hanover, VT" }, "geometry": { "type": "Point", "coordinates": [ -72.27356, 43.687736 ] } },
{ "type": "Feature", "properties": { "Name": "Concord, NH", "description": "Concord, NH" }, "geometry": { "type": "Point", "coordinates": [ -71.499023, 43.201172 ] } },
{ "type": "Feature", "properties": { "Name": "Nashua, NH", "description": "Nashua, NH" }, "geometry": { "type": "Point", "coordinates": [ -71.438599, 42.747012 ] } },
{ "type": "Feature", "properties": { "Name": "Lowell, MA", "description": "Lowell, MA" }, "geometry": { "type": "Point", "coordinates": [ -71.308136, 42.620823 ] } },
{ "type": "Feature", "properties": { "Name": "South Lowrence, MA", "description": "South Lowrence, MA" }, "geometry": { "type": "Point", "coordinates": [ -71.156387, 42.684454 ] } },
{ "type": "Feature", "properties": { "Name": "Acton, MA", "description": "Acton, MA" }, "geometry": { "type": "Point", "coordinates": [ -71.437225, 42.481213 ] } },
{ "type": "Feature", "properties": { "Name": "Westborough, MA", "description": "Westborough, MA" }, "geometry": { "type": "Point", "coordinates": [ -71.643219, 42.263082 ] } },
{ "type": "Feature", "properties": { "Name": "Farmingham, MA", "description": "Farmingham, MA" }, "geometry": { "type": "Point", "coordinates": [ -71.3974, 42.291532 ] } },
{ "type": "Feature", "properties": { "Name": "Sharon, MA", "description": "Sharon, MA" }, "geometry": { "type": "Point", "coordinates": [ -71.207886, 42.123692 ] } },
{ "type": "Feature", "properties": { "Name": "Providence, RI", "description": "Providence, RI" }, "geometry": { "type": "Point", "coordinates": [ -71.423492, 41.835805 ] } },
{ "type": "Feature", "properties": { "Name": "Lexington, MA", "description": "Lexington, MA" }, "geometry": { "type": "Point", "coordinates": [ -71.228485, 42.450821 ] } },
{ "type": "Feature", "properties": { "Name": "Boston, MA", "description": "Boston, MA" }, "geometry": { "type": "Point", "coordinates": [ -71.082916, 42.368691 ] } },
{ "type": "Feature", "properties": { "Name": "Quincy, MA", "description": "Quincy, MA" }, "geometry": { "type": "Point", "coordinates": [ -71.010132, 42.243769 ] } },
{ "type": "Feature", "properties": { "Name": "Newton, MA", "description": "Newton, MA" }, "geometry": { "type": "Point", "coordinates": [ -71.183167, 42.320986 ] } },
{ "type": "Feature", "properties": { "Name": "Amherst, MA", "description": "Amherst, MA-University" }, "geometry": { "type": "Point", "coordinates": [ -72.460327, 42.354485 ] } },
{ "type": "Feature", "properties": { "Name": "Morgan City, LA", "description": "Morgan City, LA" }, "geometry": { "type": "Point", "coordinates": [ -91.192017, 29.683281 ] } },
{ "type": "Feature", "properties": { "Name": "Fort Smith, AR", "description": "Fort Smith, AR" }, "geometry": { "type": "Point", "coordinates": [ -94.361572, 35.38905 ] } },
{ "type": "Feature", "properties": { "Name": "Beaumont, TX", "description": "Beaumont, TX-University" }, "geometry": { "type": "Point", "coordinates": [ -94.01001, 30.002517 ] } },
{ "type": "Feature", "properties": { "Name": "Denton, TX", "description": "Denton, TX-University" }, "geometry": { "type": "Point", "coordinates": [ -97.130127, 33.26625 ] } },
{ "type": "Feature", "properties": { "Name": "Amarillo, TX", "description": "Amarillo, TX" }, "geometry": { "type": "Point", "coordinates": [ -101.755371, 35.272532 ] } },
{ "type": "Feature", "properties": { "Name": "Lubbock, TX", "description": "Lubbock, TX-University" }, "geometry": { "type": "Point", "coordinates": [ -101.766357, 33.623768 ] } },
{ "type": "Feature", "properties": { "Name": "College Station, TX", "description": "College Station, TX-University" }, "geometry": { "type": "Point", "coordinates": [ -96.328125, 30.637912 ] } },
{ "type": "Feature", "properties": { "Name": "Norman, OK", "description": "Norman, OK-University" }, "geometry": { "type": "Point", "coordinates": [ -97.415771, 35.191767 ] } }
]
}
